### ISSUE TITLE
401 on requests with a url query

### ISSUE THREAD

**Issue by Kazakuri** [sotojuan/nani#1]
If you use a request that supports or requires a url query such as `browse/anime?season=winter` you get

```
{ 
  status: 401,
  error: 'unauthorized',
  error_message: 'Access token is missing' 
}
```

Probably because [this line](https://github.com/sotojuan/nani/blob/master/lib/request.js#L15) assumes that there isn't a query and appends `access_token` with a `?` when urls with already existing queries should use `&`.
Perhaps adding support for passing in am optional JSON object of params?

**Comment by sotojuan** [comment]
Sure, will work on this ASAP. To be honest I didn't even know the API that endpoints like that (my bad!).
